package com.revature.dao;

import java.util.List;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.revature.models.Movie;
import com.revature.util.HibernateUtil;

public class MovieDaoImpl implements IMovieDao {

	@Override
	public int insert(Movie m) {
		Session ses = HibernateUtil.getSession();
		Transaction tx = ses.beginTransaction();
		int pk = (int) ses.save(m);
		tx.commit();
		return pk;
	}

	@Override
	public Movie selectById(int id) {
		Session ses = HibernateUtil.getSession();
		Movie m = ses.get(Movie.class, id);
		return m;
	}

	@Override
	public List<Movie> selectAll() {
		Session ses = HibernateUtil.getSession();
		List<Movie> movies = ses.createQuery("from Movie", Movie.class).list();
		return movies;
	}

	/**
	 * TODO: query from the join table that's auto generated by Hibernate
	 * to figure out the table name then create a complex
	 * join query to pull the Movies belonging to a user from
	 */
	@Override
	public List<Movie> selectByUserId(int userId) {
		// TODO Auto-generated method stub
		return null;
	}

}