package com.revature.service;

import java.util.Scanner;

import com.revature.dao.AccountDaoImpl;
import com.revature.dao.IAccountDao;
import com.revature.models.Account;
import com.revature.models.User;

public class AccountService {
	
	// DEPENDENCY INJECTION 
	public IAccountDao adao = new AccountDaoImpl();
	
	private static Scanner scan = new Scanner(System.in);
	
	// returns an Account object, returns a User object
	public Account openAccount(User u) {
		
		// I need the User's ID for the accOwner ID property of the Account I'm creating
		
		// prompt the user to enter an initial deposit amount
		System.out.println("Please enter the initial amount you would like to deposit:");
		
		// capture the deposit value
		double deposit = scan.nextDouble();
		
		// instantiate an Account object with the initial deposit, the owner's ID and make it NOT active
		Account a = new Account(deposit, u.getId(), false);
		
		// call the insert method and return the primary key generated by the DB
		int pk = adao.insert(a);
		
		// take the object we originally created and set its ID to the PK
		a.setId(pk);
		
		// return the account object
		return a;
	}
	
	
	public boolean deposit(double depositAmount) {
		
		// some rigorous logic
		
		return false;
	}
	
	

}
